### ISSUE TITLE
Что за курс?

### ISSUE THREAD

**Issue by wpfdev** [Babadeda212/mesto#1]
Добрый день, это задание какого то курса или откуда была идея по созданию этого демо-проекта?

**Comment by Babadeda212** [comment]
Привет, это курсы Яндекс.Практикум, Вэб-разработка

вт, 16 мар. 2021 г., 11:12 wpfdev ***@***.***>:

**Comment by wpfdev** [comment]
Спасибо, неплохой материал дают на Яндекс курсах
